name: CI-CD

on: # Controls when the workflow will run
  push: # Triggers the workflow on push or pull request events but only for the main branch
    branches: [ main ]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI: # Job Name
    runs-on: ubuntu-latest # Agent that will execute the job
    steps:
      - uses: actions/checkout@v2 # Download files

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            vagnernasc88/vero-movies:latest
            vagnernasc88/vero-movies:v${{github.run_number}}
